### ISSUE TITLE
Update Node version

### ISSUE THREAD

**Issue by chrismlusk** [onedesign/craft-starter#48]
We're currently set at v10.8.0 in `.nvmrc`, but [v12 is the active version](https://nodejs.org/en/about/releases/). It looks like our new projects are using v12 anyway.

Should we bump this? If so, is v12.18.0 fine?

**Comment by brianjhanson** [comment]
Yeah, we can bump it. In general, I think our starter should support whatever the active LTS version is depending on [their schedule](https://nodejs.org/en/about/releases/)

**Comment by brianjhanson** [comment]
Updated the `.nvmrc` to `lts/*` in #39
