### ISSUE TITLE
Add env variables for common plugins and services

### ISSUE THREAD

**Issue by chrismlusk** [onedesign/craft-starter#49]
We tend to use a lot of the same plugins and services — S3, Imgix, CloudFront, etc. — on a lot of our projects. I think expanding `.env.example` to have vars for these things will:

- serve as sort of a checklist when getting started
- help our naming be a bit more consistent between projects

```env
# AWS S3 settings
S3_ACCESS_KEY_ID=
S3_SECRET_ACCESS_KEY=
S3_BUCKET_NAME=
S3_REGION=
S3_SUBFOLDER=

# CloudFront settings
CLOUDFRONT_DOMAIN=
CLOUDFRONT_DISTRIBUTION_ID=
CLOUDFRONT_PATH_PREFIX=

# IMGIX settings
IMGIX_API_KEY=
IMGIX_SECURITY_TOKEN=
IMGIX_SOURCE_DOMAIN=
```

**Comment by brianjhanson** [comment]
Minor edits, ```
# AWS S3 settings
S3_ACCESS_KEY_ID=
S3_SECRET_ACCESS_KEY=
S3_BUCKET_NAME=
S3_REGION=
S3_SUBFOLDER=

# CloudFront settings
CLOUDFRONT_URL=
CLOUDFRONT_DISTRIBUTION_ID=

# IMGIX settings
IMGIX_API_KEY=
IMGIX_SECURITY_TOKEN=
IMGIX_SOURCE_DOMAIN=
```

* I like `CLOUDFRONT_URL` over `DOMAIN` just because it should be a full URL
* Removed the path prefix, because this changes by volume
