### ISSUE TITLE
Normalize.css Import Statement not working

### ISSUE THREAD

**Issue by ryanpowszok** [onedesign/craft-starter#8]
In main.scss, the import statement for normalize is not working properly. `@import 'normalize.css';`

The way normalize is being imported its looking for a separate file and I get the following error in Chrome -> http://localhost:3000/dist/styles/normalize.css 404 (Not Found)

Changing the import statement to `@import 'normalize.css/normalize';` resolves the issue but I get a new error in my terminal console:

DEPRECATION WARNING Including .css files with @import is non-standard behaviour which will be removed in future versions of LibSass. Use a custom importer to maintain this behaviour. Check your implementations documentation on how to create a custom importer.

It may be better to use a scss version of normalize such as https://github.com/JohnAlbin/normalize-scss

**Comment by brianjhanson** [comment]
Hey @ryanpowszok thanks for calling this out! 

That deprecation error is a bit of a blip that is in the version of libsass used by Blendid. [You can read the full lib sass thread here](https://github.com/sass/node-sass/issues/2362) but the critical comment is [way down at the bottom](https://github.com/sass/node-sass/issues/2362#issuecomment-396239814). 

Long story short, we're just ignoring it hoping Blendid updates their versions sometime in the near future 🤞

**Comment by brianjhanson** [comment]
I don't believe this is an issue after #39
